"""Impact measurement and SDG alignment engine.

Provides IRIS+ 5.3c catalog access, SDG mapping, 5-Dimension assessment,
and impact reporting for VC/impact investment funds.
"""

from openharness.impact.climate_accounting import (
    ActivityData,
    GHGInventory,
    RenewableCertificate,
    calculate_ghg_inventory,
    scope3_estimate,
    three_year_comparison,
)
from openharness.impact.data_quality import (
    DataQualityAssessment,
    apply_quality_assessment,
    assess_metric_record_quality,
)
from openharness.impact.emission_factors import (
    EmissionFactorCatalogV2,
    EmissionFactorRevision,
    apply_catalog_to_inventory,
    default_factor_catalog,
    factor_sensitivity,
    summarise_sensitivity,
)
from openharness.impact.evidence_graph import (
    EvidenceGraph,
    build_evidence_graph,
)
from openharness.impact.evidence_workflow import (
    ExtractionReviewPolicy,
    ReviewQueue,
    ReviewQueueItem,
)
from openharness.impact.exit_impact import (
    ExitDurabilityRisk,
    ExitImpactPlan,
    ExitImpactScore,
    PostExitFollowUp,
    build_exit_plan,
    score_exit_impact,
)
from openharness.impact.greenwashing_reviewer import (
    ClaimReviewItem,
    GreenwashingReviewerOutput,
    review_company_claims,
)
from openharness.impact.investee_collection import (
    InvesteeQuestionnaireSchema,
    generate_investee_questionnaire_schema,
)
from openharness.impact.lp_narrative import (
    LPNarrativeReport,
    LPNarrativeRequest,
    LPQuestion,
    LPQuestionWorkspace,
    generate_lp_narrative,
)
from openharness.impact.lca import (
    LCA_FRAMEWORK_SOURCES,
    LCAReadiness,
    LCAResult,
    LCAScenario,
    LCAStudy,
    LCCResult,
    LCMPlan,
    LCSAResult,
    LCIFlow,
    LifecycleCostLine,
    SocialIndicator,
    SocialLCAResult,
    assess_lca_readiness,
    assess_social_lca,
    build_lcm_plan,
    calculate_lcc,
    calculate_lca,
    calculate_lcsa,
    list_lcia_methods,
    run_lca_sensitivity,
)
from openharness.impact.models import (
    Assessment,
    Company,
    DimensionTags,
    FiveDimensionScore,
    ImpactClaim,
    Metric,
    MetricRecord,
    SDGGoal,
    SDGTarget,
)
from openharness.impact.portfolio_nlq import (
    ApprovedDataPolicy,
    PortfolioNLQEngine,
    QueryAnswer,
    QueryIntent,
    parse_intent,
)
from openharness.impact.roadmap_v2 import (
    build_lp_export_bundle,
    build_review_queue,
    issue_collection_link,
    run_control_checks,
)
from openharness.impact.stakeholder_voice import (
    BeneficiaryFeedbackQuality,
    ConsentRecord,
    LeanDataTemplate,
    build_lean_data_survey,
    link_feedback_to_claims,
    revoke_consent,
    score_feedback_quality,
)
from openharness.impact.standards_registry import (
    StandardVersion,
    StandardsRegistry,
    default_standards_registry,
    get_default_standard,
)
from openharness.impact.verification_workspace import (
    VerificationComment,
    VerificationFinding,
    VerificationWorkspace,
    open_workspace,
)

__all__ = [
    "ApprovedDataPolicy",
    "ActivityData",
    "Assessment",
    "BeneficiaryFeedbackQuality",
    "ClaimReviewItem",
    "Company",
    "ConsentRecord",
    "DataQualityAssessment",
    "DimensionTags",
    "EmissionFactorCatalogV2",
    "EmissionFactorRevision",
    "EvidenceGraph",
    "ExitDurabilityRisk",
    "ExitImpactPlan",
    "ExitImpactScore",
    "ExtractionReviewPolicy",
    "FiveDimensionScore",
    "GHGInventory",
    "GreenwashingReviewerOutput",
    "ImpactClaim",
    "InvesteeQuestionnaireSchema",
    "LPNarrativeReport",
    "LPNarrativeRequest",
    "LPQuestion",
    "LPQuestionWorkspace",
    "LCAReadiness",
    "LCA_FRAMEWORK_SOURCES",
    "LCAResult",
    "LCAScenario",
    "LCAStudy",
    "LCCResult",
    "LCMPlan",
    "LCSAResult",
    "LCIFlow",
    "LifecycleCostLine",
    "LeanDataTemplate",
    "Metric",
    "MetricRecord",
    "PortfolioNLQEngine",
    "PostExitFollowUp",
    "QueryAnswer",
    "QueryIntent",
    "ReviewQueue",
    "ReviewQueueItem",
    "RenewableCertificate",
    "SDGGoal",
    "SDGTarget",
    "SocialIndicator",
    "SocialLCAResult",
    "StandardVersion",
    "StandardsRegistry",
    "VerificationComment",
    "VerificationFinding",
    "VerificationWorkspace",
    "apply_catalog_to_inventory",
    "apply_quality_assessment",
    "assess_metric_record_quality",
    "build_evidence_graph",
    "build_exit_plan",
    "build_lean_data_survey",
    "build_lp_export_bundle",
    "build_lcm_plan",
    "build_review_queue",
    "calculate_ghg_inventory",
    "calculate_lcc",
    "calculate_lca",
    "calculate_lcsa",
    "default_factor_catalog",
    "default_standards_registry",
    "factor_sensitivity",
    "generate_investee_questionnaire_schema",
    "generate_lp_narrative",
    "list_lcia_methods",
    "get_default_standard",
    "issue_collection_link",
    "link_feedback_to_claims",
    "open_workspace",
    "parse_intent",
    "review_company_claims",
    "revoke_consent",
    "run_control_checks",
    "run_lca_sensitivity",
    "score_exit_impact",
    "score_feedback_quality",
    "assess_lca_readiness",
    "assess_social_lca",
    "scope3_estimate",
    "summarise_sensitivity",
    "three_year_comparison",
]
