"""W2.1-W2.3: decision-first report — design system, layout, audiences."""

from __future__ import annotations

import copy
import re

import pytest

from openharness.impact.pipeline import assess_file, sample_deck_path
from openharness.impact.report_templates.decision_report import (
    SPECS,
    build_view,
    render_decision_report,
)

ATTR = '"><svg onload=alert(1)>'
TAG = "<img src=x onerror=alert(1)>"


@pytest.fixture(scope="module")
def pig_data() -> dict:
    return assess_file(sample_deck_path("pig-farm")).report_data


def _ids(html: str) -> set[str]:
    return set(re.findall(r'\bid="([^"]+)"', html))


def test_first_screen_is_decision_first(pig_data):
    html = render_decision_report(pig_data)
    order = [html.index(marker) for marker in ('id="sec-verdict"', 'class="kpis"', 'id="sec-mind"', 'id="sec-5d"')]
    assert order == sorted(order)
    assert "Not IC-ready" in html  # pig farm is data-light, not a negative finding
    assert "missing data" in html


@pytest.mark.parametrize("audience", list(SPECS))
def test_audiences_render_only_their_sections(pig_data, audience):
    html = render_decision_report(pig_data, audience=audience)
    spec = SPECS[audience]
    assert ('id="sec-verdict"' in html) == spec.show_gate
    assert ('id="sec-greenwashing"' in html) == spec.show_greenwashing
    if not spec.show_greenwashing:
        assert "Greenwashing risk" not in html
    if audience == "public":
        assert "Confidential" not in html


def test_lp_ready_report_type_maps_to_lp(pig_data):
    data = dict(pig_data, report_type="lp_ready", audience="full")
    assert build_view(data)["audience"] == "lp"


def test_offline_and_accessible(pig_data):
    html = render_decision_report(pig_data)
    assert "<script src" not in html and "cdn.plot.ly" not in html
    assert re.search(r'<html lang="en"', html)
    for head in re.findall(r"<thead>(.*?)</thead>", html, re.S):
        assert all('scope="col"' in th for th in re.findall(r"<th[^>]*>", head))
    toc = re.search(r'<nav class="card no-print".*?</nav>', html, re.S).group(0)
    assert all(link in _ids(html) for link in re.findall(r'href="#([^"]+)"', toc))
    # every chart has a text alternative and a table twin
    assert html.count('role="img"') >= 2
    assert html.count("Show as table") >= 2


def test_user_text_is_escaped(pig_data):
    data = copy.deepcopy(pig_data)
    data["company"]["name"] = f"Acme {ATTR}"
    data["company"]["sector"] = f"farm {TAG}"
    data["impact_claims"].append({"text": f"We help {TAG}", "category": "outcome"})
    data["company"]["reported_metrics"]["OI8869"] = f"142 {ATTR}"
    data["impact_analysis"]["risks"].append(f"Disclosed: run-off {TAG}")
    html = render_decision_report(data)
    assert ATTR not in html and TAG not in html


def test_dark_theme_and_branding_are_safe(pig_data):
    data = dict(pig_data, theme="dark")
    html = render_decision_report(
        data,
        branding={"fund_name": "Meridian", "primary_color": "red;}body{display:none",
                  "logo_url": "javascript:alert(1)", "footer_text": "For LPs only",
                  "hide_attribution": True},
    )
    assert '<html lang="en" data-theme="dark">' in html
    assert "display:none" not in html and "javascript:" not in html
    assert "Meridian" in html and "For LPs only" in html
    assert "Generated by Impact Vision" not in html
    ok = render_decision_report(pig_data, branding={"primary_color": "#0a7f5a"})
    assert "--brand: #0a7f5a" in ok


def test_report_without_optional_sections_still_renders():
    minimal = {"company": {"name": "Bare Co", "reported_metrics": {}}, "generated_at": "2026-10-06"}
    html = render_decision_report(minimal)
    assert "Bare Co" in html and 'id="sec-appendix"' in html


def test_pdf_export_falls_back_with_install_hint(monkeypatch, tmp_path):
    import builtins

    from openharness.impact.report_templates import pdf

    real_import = builtins.__import__

    def no_engines(name, *args, **kwargs):
        if name.startswith(("playwright", "weasyprint")):
            raise ImportError(name)
        return real_import(name, *args, **kwargs)

    monkeypatch.setattr(builtins, "__import__", no_engines)
    with pytest.raises(pdf.PdfUnavailable) as exc:
        pdf.html_to_pdf("<html><body>x</body></html>", tmp_path / "r.pdf")
    assert "impact-vision[pdf]" in str(exc.value)


def test_print_css_hides_table_twins_and_avoids_row_breaks():
    from openharness.impact.report_templates.decision_report import design_css

    css = design_css()
    assert "details.twin" in css
    assert "@page" in css and "tr, .verdict { break-inside: avoid" in css
