"""SFDR Principal Adverse Impact (PAI) indicators.

The EU Sustainable Finance Disclosure Regulation (SFDR) requires 14 mandatory
Principal Adverse Impact indicators for financial market participants.

Reference: EU Delegated Regulation (EU) 2022/1288, Annex I
"""

from __future__ import annotations

from pydantic import BaseModel, Field


class SFDRIndicator(BaseModel):
    """An SFDR PAI indicator."""
    number: int
    name: str
    category: str  # "climate", "environmental", "social", "anti-corruption"
    metric: str
    unit: str = ""
    description: str = ""
    mandatory: bool = True
    iris_cross_refs: list[str] = Field(default_factory=list)
    data_points: list[str] = Field(default_factory=list)


PAI_INDICATORS: list[SFDRIndicator] = [
    # Climate and environment-related
    SFDRIndicator(
        number=1,
        name="GHG emissions",
        category="climate",
        metric="Scope 1, 2, and 3 GHG emissions; Total GHG emissions",
        unit="tCO2e",
        description="Scope 1, 2, and total from Scope 3 GHG emissions generated by investee companies",
        iris_cross_refs=["OI1479", "OI4112"],
        data_points=["Scope 1 GHG emissions", "Scope 2 GHG emissions", "Scope 3 GHG emissions", "Total GHG emissions"],
    ),
    SFDRIndicator(
        number=2,
        name="Carbon footprint",
        category="climate",
        metric="Carbon footprint of the portfolio",
        unit="tCO2e / EUR million invested",
        description="Carbon footprint = total GHG emissions of investee / current value of investment / total AUM",
        data_points=["Total GHG emissions", "Enterprise value", "Current value of investment"],
    ),
    SFDRIndicator(
        number=3,
        name="GHG intensity of investee companies",
        category="climate",
        metric="GHG intensity",
        unit="tCO2e / EUR million revenue",
        description="GHG intensity of investee companies = GHG emissions / revenue",
        data_points=["Total GHG emissions", "Revenue"],
    ),
    SFDRIndicator(
        number=4,
        name="Exposure to companies active in the fossil fuel sector",
        category="climate",
        metric="Share of investments in fossil fuel companies",
        unit="%",
        description="Share of investments in companies active in the fossil fuel sector",
        data_points=["Revenue from fossil fuels", "Exploration/extraction/refining/processing activities"],
    ),
    SFDRIndicator(
        number=5,
        name="Share of non-renewable energy consumption and production",
        category="climate",
        metric="Share of non-renewable energy consumption and production",
        unit="%",
        description="Share of non-renewable energy consumption and non-renewable energy production of investee companies",
        data_points=["Non-renewable energy consumption", "Total energy consumption", "Non-renewable energy production", "Total energy production"],
    ),
    SFDRIndicator(
        number=6,
        name="Energy consumption intensity per high impact climate sector",
        category="climate",
        metric="Energy consumption in GWh per million EUR revenue per NACE sector",
        unit="GWh / EUR million",
        description="Energy consumption intensity per high impact climate sector (NACE Sections A-H, L)",
        data_points=["Energy consumption by NACE sector", "Revenue by NACE sector"],
    ),
    SFDRIndicator(
        number=7,
        name="Activities negatively affecting biodiversity-sensitive areas",
        category="environmental",
        metric="Share of investments in companies with sites near biodiversity-sensitive areas",
        unit="%",
        description="Share of investments in companies with sites/operations in or near biodiversity-sensitive areas where the activities negatively affect those areas",
        data_points=["Operations near protected areas", "Natura 2000 sites", "UNESCO World Heritage sites"],
    ),
    SFDRIndicator(
        number=8,
        name="Emissions to water",
        category="environmental",
        metric="Tonnes of emissions to water generated by investee companies",
        unit="tonnes / EUR million invested",
        description="Tonnes of emissions to water generated by investee companies per million EUR invested",
        data_points=["Emissions to water (tonnes)", "Types of pollutants"],
    ),
    SFDRIndicator(
        number=9,
        name="Hazardous waste and radioactive waste ratio",
        category="environmental",
        metric="Tonnes of hazardous waste and radioactive waste",
        unit="tonnes / EUR million invested",
        description="Tonnes of hazardous waste and radioactive waste generated by investee companies per million EUR invested",
        data_points=["Hazardous waste (tonnes)", "Radioactive waste (tonnes)"],
    ),
    # Social and employee matters
    SFDRIndicator(
        number=10,
        name="Violations of UNGC principles and OECD Guidelines for MNEs",
        category="social",
        metric="Share of investments in companies that have been involved in violations",
        unit="%",
        description="Share of investments in investee companies that have been involved in violations of the UNGC principles or OECD Guidelines for Multinational Enterprises",
        data_points=["UNGC violations", "OECD Guidelines violations", "Corrective actions taken"],
    ),
    SFDRIndicator(
        number=11,
        name="Lack of processes and compliance mechanisms to monitor UNGC and OECD compliance",
        category="social",
        metric="Share of investments in companies without UNGC/OECD compliance policies",
        unit="%",
        description="Share of investments in investee companies without policies to monitor compliance with the UNGC principles or OECD Guidelines for MNEs or grievance/complaints handling mechanisms",
        data_points=["UNGC compliance policy", "OECD compliance policy", "Grievance mechanism"],
    ),
    SFDRIndicator(
        number=12,
        name="Unadjusted gender pay gap",
        category="social",
        metric="Average unadjusted gender pay gap of investee companies",
        unit="%",
        description="Average unadjusted gender pay gap of investee companies",
        iris_cross_refs=["OI1582"],
        data_points=["Male average pay", "Female average pay", "Gender pay gap ratio"],
    ),
    SFDRIndicator(
        number=13,
        name="Board gender diversity",
        category="social",
        metric="Average ratio of female to male board members",
        unit="%",
        description="Average ratio of female to male board members in investee companies",
        iris_cross_refs=["OI1075", "OI6213"],
        data_points=["Female board members", "Total board members", "Female:male ratio"],
    ),
    SFDRIndicator(
        number=14,
        name="Exposure to controversial weapons",
        category="social",
        metric="Share of investments in companies involved in controversial weapons",
        unit="%",
        description="Share of investments in investee companies involved in the manufacture or selling of controversial weapons (anti-personnel mines, cluster munitions, chemical weapons, biological weapons)",
        data_points=["Involvement in anti-personnel mines", "Cluster munitions", "Chemical weapons", "Biological weapons"],
    ),
]


OPTIONAL_PAI_INDICATORS: list[SFDRIndicator] = [
    # Environment - optional (Table 2 of Annex I)
    SFDRIndicator(
        number=15, name="GHG intensity of investee countries", category="climate",
        metric="GHG intensity of investee countries", unit="tCO2e/EUR M GDP", mandatory=False,
        data_points=["Country GDP", "Country GHG emissions"],
    ),
    SFDRIndicator(
        number=16, name="Investee countries subject to social violations", category="social",
        metric="Number of countries subject to social violations", mandatory=False,
        data_points=["EU sanctions list", "UNGC violations by country"],
    ),
    SFDRIndicator(
        number=17, name="Exposure to fossil fuel through real estate", category="climate",
        metric="Share of real estate assets in fossil fuel exposure", unit="%", mandatory=False,
        data_points=["Real estate energy source"],
    ),
    SFDRIndicator(
        number=18, name="Exposure to energy-inefficient real estate", category="climate",
        metric="Share of real estate with EPC below C", unit="%", mandatory=False,
        data_points=["EPC rating", "Energy efficiency certificates"],
    ),
    # Biodiversity optional
    SFDRIndicator(
        number=19, name="Deforestation", category="environmental",
        metric="Share of investments linked to deforestation", unit="%", mandatory=False,
        data_points=["Supply chain deforestation risk", "Commodity sourcing data"],
    ),
    # Water optional
    SFDRIndicator(
        number=20, name="Untreated discharged waste water", category="environmental",
        metric="Share of investees discharging untreated waste water", unit="%", mandatory=False,
        data_points=["Waste water treatment", "Discharge volumes"],
    ),
    # Social optional
    SFDRIndicator(
        number=21, name="Lack of human rights policy", category="social",
        metric="Share of investments without a human rights policy", unit="%", mandatory=False,
        data_points=["Human rights policy", "Due diligence process"],
    ),
    SFDRIndicator(
        number=22, name="Lack of anti-corruption and anti-bribery policy", category="anti-corruption",
        metric="Share of investments without anti-corruption policies", unit="%", mandatory=False,
        data_points=["Anti-corruption policy", "Whistleblower mechanism"],
    ),
    SFDRIndicator(
        number=23, name="Excessive CEO pay ratio", category="social",
        metric="Average ratio of CEO compensation to median employee compensation", mandatory=False,
        data_points=["CEO total compensation", "Median employee compensation"],
    ),
]


def get_pai_indicators(mandatory_only: bool = True) -> list[SFDRIndicator]:
    if mandatory_only:
        return [i for i in PAI_INDICATORS if i.mandatory]
    return PAI_INDICATORS + OPTIONAL_PAI_INDICATORS


def assess_sfdr_compliance(
    reported_data: dict[str, str] | None = None,
    company_description: str = "",
    document_text: str = "",
) -> dict:
    """Assess which SFDR PAI indicators a company can report on.

    Returns per-indicator compliance status and data gaps.
    """
    text = f"{company_description} {document_text}".lower()
    reported = reported_data or {}

    indicator_keywords = {
        1: ["scope 1", "scope 2", "scope 3", "ghg emission", "greenhouse gas", "carbon emission"],
        2: ["carbon footprint", "portfolio carbon"],
        3: ["ghg intensity", "carbon intensity", "emission intensity"],
        4: ["fossil fuel", "oil", "gas", "coal", "exploration"],
        5: ["non-renewable", "renewable energy", "energy mix"],
        6: ["energy consumption", "energy intensity", "NACE"],
        7: ["biodiversity", "protected area", "natura 2000", "UNESCO"],
        8: ["emissions to water", "water pollution", "effluent"],
        9: ["hazardous waste", "radioactive waste"],
        10: ["UNGC", "UN global compact", "OECD guidelines", "violation"],
        11: ["compliance mechanism", "grievance", "complaint handling"],
        12: ["gender pay gap", "pay equity", "wage gap"],
        13: ["board diversity", "female board", "board gender"],
        14: ["controversial weapons", "cluster munitions", "anti-personnel"],
    }

    result = {
        "framework": "SFDR PAI (14 Mandatory Indicators)",
        "indicators": [],
        "total": 14,
        "addressed": 0,
        "gaps": 0,
    }

    for ind in PAI_INDICATORS:
        addressed = False
        evidence: list[str] = []

        kws = indicator_keywords.get(ind.number, [])
        hits = [kw for kw in kws if kw in text]
        if len(hits) >= 1:
            addressed = True
            evidence.extend(hits)

        if ind.iris_cross_refs:
            for ref in ind.iris_cross_refs:
                if ref in reported:
                    addressed = True
                    evidence.append(f"IRIS+ {ref} reported")

        ind_result = {
            "number": ind.number,
            "name": ind.name,
            "category": ind.category,
            "addressed": addressed,
            "evidence": evidence,
            "data_points_needed": ind.data_points if not addressed else [],
        }
        result["indicators"].append(ind_result)

        if addressed:
            result["addressed"] += 1
        else:
            result["gaps"] += 1

    result["coverage_pct"] = round(result["addressed"] / result["total"] * 100, 1)
    return result


# ---------------------------------------------------------------------------
# Article 6 / 8 / 9 Fund Classification
# ---------------------------------------------------------------------------

_ARTICLE_DESCRIPTIONS = {
    6: "No ESG integration commitments (basic risk disclosure only)",
    8: "Promotes E/S characteristics alongside financial return (light green)",
    9: "Sustainable investment as its objective (dark green)",
}


def classify_sfdr_article(
    description: str = "",
    document_text: str = "",
    fund_name: str = "",
    has_sustainability_objective: bool = False,
    pct_sustainable_investments: float | None = None,
) -> dict:
    """Classify a fund under SFDR Article 6, 8, or 9.

    Article 9 requires the fund to have sustainable investment as its *objective*
    with measurable targets. Article 8 promotes E/S characteristics without making
    sustainable investment the primary objective. Article 6 is the default.
    """
    text = f"{description} {document_text} {fund_name}".lower()

    art9_signals = [
        "sustainable investment objective", "article 9", "art 9", "dark green",
        "sustainable investment as its objective", "taxonomy-aligned",
    ]
    art8_signals = [
        "promotes environmental", "promotes social", "esg integration",
        "article 8", "art 8", "light green", "e/s characteristics",
        "environmental and social characteristics",
    ]

    art9_hits = [s for s in art9_signals if s in text]
    art8_hits = [s for s in art8_signals if s in text]

    if has_sustainability_objective or art9_hits:
        article = 9
        confidence = "high" if has_sustainability_objective else "medium"
    elif art8_hits or (pct_sustainable_investments is not None and pct_sustainable_investments > 0):
        article = 8
        confidence = "high" if len(art8_hits) >= 2 else "medium"
    else:
        article = 6
        confidence = "high" if not art8_hits and not art9_hits else "low"

    requirements: list[str] = []
    if article == 9:
        requirements = [
            "Disclose how the sustainable investment objective is achieved",
            "Show that investments do no significant harm (DNSH) to other E/S objectives",
            "Report on all 14 mandatory PAI indicators",
            "Disclose proportion of investments aligned with EU Taxonomy",
            "Pre-contractual and periodic disclosures per Annex III/V",
        ]
    elif article == 8:
        requirements = [
            "Disclose how E/S characteristics are promoted",
            "Report on relevant PAI indicators (at minimum those related to promoted characteristics)",
            "If making sustainable investments, apply DNSH criteria",
            "Pre-contractual and periodic disclosures per Annex II/IV",
        ]
    else:
        requirements = [
            "Disclose how sustainability risks are integrated into investment decisions",
            "State whether PAI is considered (comply or explain)",
        ]

    return {
        "article": article,
        "description": _ARTICLE_DESCRIPTIONS[article],
        "confidence": confidence,
        "evidence": art9_hits or art8_hits or [],
        "requirements": requirements,
        "pct_sustainable_investments": pct_sustainable_investments,
    }


def assess_sfdr_entity_vs_fund(
    entity_description: str = "",
    fund_descriptions: list[dict[str, str]] | None = None,
) -> dict:
    """Distinguish entity-level vs product-level SFDR obligations.

    Entity-level: applies to the financial market participant as a whole.
    Product-level: applies per fund/product under management.
    """
    entity_obligations = [
        "Publish principal adverse impact statement (Art. 4) or explain why not",
        "Disclose sustainability risk integration policy (Art. 3)",
        "Disclose remuneration policy consistency with sustainability risk integration (Art. 5)",
    ]

    fund_results: list[dict] = []
    for fund in (fund_descriptions or []):
        cls = classify_sfdr_article(
            description=fund.get("description", ""),
            fund_name=fund.get("name", ""),
        )
        fund_results.append({"name": fund.get("name", ""), **cls})

    return {
        "entity_level": {
            "obligations": entity_obligations,
            "applies_to": "Financial Market Participant (firm-wide)",
        },
        "product_level": {
            "funds_classified": len(fund_results),
            "funds": fund_results,
        },
    }
