"""SFDR Principal Adverse Impact (PAI) indicators.

The EU Sustainable Finance Disclosure Regulation (SFDR) requires 14 mandatory
Principal Adverse Impact indicators for financial market participants.

Reference: EU Delegated Regulation (EU) 2022/1288, Annex I

Status note (verified 2026-07): SFDR 1.0 (Article 6/8/9 + these PAIs) remains
the law in force. The SFDR 2.0 recast — a three-category product labelling
regime ("Sustainable" / "Transition" / "ESG Basics") that would repeal
Delegated Regulation 2022/1288 — is still in the legislative pipeline: the
Council agreed its negotiating position on 2026-06-24 (proposing a 24-month
implementation period), trilogue starts late 2026, and application is not
expected before ~2029. Keep classifying against Article 6/8/9 until the recast
is adopted.
"""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field


class SFDRIndicator(BaseModel):
    """An SFDR PAI indicator."""
    number: int
    name: str
    category: str  # "climate", "environmental", "social", "anti-corruption"
    metric: str
    unit: str = ""
    description: str = ""
    mandatory: bool = True
    iris_cross_refs: list[str] = Field(default_factory=list)
    data_points: list[str] = Field(default_factory=list)


class SFDRArticleClassification(BaseModel):
    """SFDR Article 6/8/9 fund classification result."""
    article: int = Field(description="SFDR article number (6, 8, or 9)")
    description: str = ""
    confidence: str = "medium"
    evidence: list[str] = Field(default_factory=list)
    requirements: list[str] = Field(default_factory=list)
    pct_sustainable_investments: float | None = None


PAI_INDICATORS: list[SFDRIndicator] = [
    # Climate and environment-related
    SFDRIndicator(
        number=1,
        name="GHG emissions",
        category="climate",
        metric="Scope 1, 2, and 3 GHG emissions; Total GHG emissions",
        unit="tCO2e",
        description="Scope 1, 2, and total from Scope 3 GHG emissions generated by investee companies",
        iris_cross_refs=["OI1479", "OI4112"],
        data_points=["Scope 1 GHG emissions", "Scope 2 GHG emissions", "Scope 3 GHG emissions", "Total GHG emissions"],
    ),
    SFDRIndicator(
        number=2,
        name="Carbon footprint",
        category="climate",
        metric="Carbon footprint of the portfolio",
        unit="tCO2e / EUR million invested",
        description="Carbon footprint = total GHG emissions of investee / current value of investment / total AUM",
        iris_cross_refs=["OI4112", "OI1479"],  # Scope 1 + Scope 2 used as numerator
        data_points=["Total GHG emissions", "Enterprise value", "Current value of investment"],
    ),
    SFDRIndicator(
        number=3,
        name="GHG intensity of investee companies",
        category="climate",
        metric="GHG intensity",
        unit="tCO2e / EUR million revenue",
        description="GHG intensity of investee companies = GHG emissions / revenue",
        iris_cross_refs=["OI4112", "OI1479", "FP4761"],  # GHG / Revenue
        data_points=["Total GHG emissions", "Revenue"],
    ),
    SFDRIndicator(
        number=4,
        name="Exposure to companies active in the fossil fuel sector",
        category="climate",
        metric="Share of investments in fossil fuel companies",
        unit="%",
        description="Share of investments in companies active in the fossil fuel sector",
        iris_cross_refs=["OD8350", "FP4761"],  # Client model / Revenue mix
        data_points=["Revenue from fossil fuels", "Exploration/extraction/refining/processing activities"],
    ),
    SFDRIndicator(
        number=5,
        name="Share of non-renewable energy consumption and production",
        category="climate",
        metric="Share of non-renewable energy consumption and production",
        unit="%",
        description="Share of non-renewable energy consumption and non-renewable energy production of investee companies",
        iris_cross_refs=["OI8825", "OI1496", "OI3324", "OI3781"],
        data_points=["Non-renewable energy consumption", "Total energy consumption", "Non-renewable energy production", "Total energy production"],
    ),
    SFDRIndicator(
        number=6,
        name="Energy consumption intensity per high impact climate sector",
        category="climate",
        metric="Energy consumption in GWh per million EUR revenue per NACE sector",
        unit="GWh / EUR million",
        description="Energy consumption intensity per high impact climate sector (NACE Sections A-H, L)",
        iris_cross_refs=["OI8825", "FP4761"],
        data_points=["Energy consumption by NACE sector", "Revenue by NACE sector"],
    ),
    SFDRIndicator(
        number=7,
        name="Activities negatively affecting biodiversity-sensitive areas",
        category="environmental",
        metric="Share of investments in companies with sites near biodiversity-sensitive areas",
        unit="%",
        description="Share of investments in companies with sites/operations in or near biodiversity-sensitive areas where the activities negatively affect those areas",
        iris_cross_refs=["PI3468", "OI4324"],  # Land use / community policy as proxies
        data_points=["Operations near protected areas", "Natura 2000 sites", "UNESCO World Heritage sites"],
    ),
    SFDRIndicator(
        number=8,
        name="Emissions to water",
        category="environmental",
        metric="Tonnes of emissions to water generated by investee companies",
        unit="tonnes / EUR million invested",
        description="Tonnes of emissions to water generated by investee companies per million EUR invested",
        iris_cross_refs=["OI0386", "OI1054"],  # Water discharged / wastewater removed proxies
        data_points=["Emissions to water (tonnes)", "Types of pollutants"],
    ),
    SFDRIndicator(
        number=9,
        name="Hazardous waste and radioactive waste ratio",
        category="environmental",
        metric="Tonnes of hazardous waste and radioactive waste",
        unit="tonnes / EUR million invested",
        description="Tonnes of hazardous waste and radioactive waste generated by investee companies per million EUR invested",
        iris_cross_refs=["OI1346"],  # Hazardous waste produced
        data_points=["Hazardous waste (tonnes)", "Radioactive waste (tonnes)"],
    ),
    # Social and employee matters
    SFDRIndicator(
        number=10,
        name="Violations of UNGC principles and OECD Guidelines for MNEs",
        category="social",
        metric="Share of investments in companies that have been involved in violations",
        unit="%",
        description="Share of investments in investee companies that have been involved in violations of the UNGC principles or OECD Guidelines for Multinational Enterprises",
        iris_cross_refs=["OI4753", "OI4324"],
        data_points=["UNGC violations", "OECD Guidelines violations", "Corrective actions taken"],
    ),
    SFDRIndicator(
        number=11,
        name="Lack of processes and compliance mechanisms to monitor UNGC and OECD compliance",
        category="social",
        metric="Share of investments in companies without UNGC/OECD compliance policies",
        unit="%",
        description="Share of investments in investee companies without policies to monitor compliance with the UNGC principles or OECD Guidelines for MNEs or grievance/complaints handling mechanisms",
        iris_cross_refs=["OI4753", "OI5049"],  # Whistleblower + grievance / feedback
        data_points=["UNGC compliance policy", "OECD compliance policy", "Grievance mechanism"],
    ),
    SFDRIndicator(
        number=12,
        name="Unadjusted gender pay gap",
        category="social",
        metric="Average unadjusted gender pay gap of investee companies",
        unit="%",
        description="Average unadjusted gender pay gap of investee companies",
        iris_cross_refs=["OI1582"],
        data_points=["Male average pay", "Female average pay", "Gender pay gap ratio"],
    ),
    SFDRIndicator(
        number=13,
        name="Board gender diversity",
        category="social",
        metric="Average ratio of female to male board members",
        unit="%",
        description="Average ratio of female to male board members in investee companies",
        iris_cross_refs=["OI1075", "OI6213"],
        data_points=["Female board members", "Total board members", "Female:male ratio"],
    ),
    SFDRIndicator(
        number=14,
        name="Exposure to controversial weapons",
        category="social",
        metric="Share of investments in companies involved in controversial weapons",
        unit="%",
        description="Share of investments in investee companies involved in the manufacture or selling of controversial weapons (anti-personnel mines, cluster munitions, chemical weapons, biological weapons)",
        iris_cross_refs=["OD8350"],  # Client model / business activity classification
        data_points=["Involvement in anti-personnel mines", "Cluster munitions", "Chemical weapons", "Biological weapons"],
    ),
]


OPTIONAL_PAI_INDICATORS: list[SFDRIndicator] = [
    # Environment - optional (Table 2 of Annex I)
    SFDRIndicator(
        number=15, name="GHG intensity of investee countries", category="climate",
        metric="GHG intensity of investee countries", unit="tCO2e/EUR M GDP", mandatory=False,
        iris_cross_refs=["OI4112"],
        data_points=["Country GDP", "Country GHG emissions"],
    ),
    SFDRIndicator(
        number=16, name="Investee countries subject to social violations", category="social",
        metric="Number of countries subject to social violations", mandatory=False,
        iris_cross_refs=["OI4753"],
        data_points=["EU sanctions list", "UNGC violations by country"],
    ),
    SFDRIndicator(
        number=17, name="Exposure to fossil fuel through real estate", category="climate",
        metric="Share of real estate assets in fossil fuel exposure", unit="%", mandatory=False,
        iris_cross_refs=["OI8825"],
        data_points=["Real estate energy source"],
    ),
    SFDRIndicator(
        number=18, name="Exposure to energy-inefficient real estate", category="climate",
        metric="Share of real estate with EPC below C", unit="%", mandatory=False,
        iris_cross_refs=["OI8825", "OI4112"],
        data_points=["EPC rating", "Energy efficiency certificates"],
    ),
    # Biodiversity optional
    SFDRIndicator(
        number=19, name="Deforestation", category="environmental",
        metric="Share of investments linked to deforestation", unit="%", mandatory=False,
        iris_cross_refs=["PI3468", "OI4324"],
        data_points=["Supply chain deforestation risk", "Commodity sourcing data"],
    ),
    # Water optional
    SFDRIndicator(
        number=20, name="Untreated discharged waste water", category="environmental",
        metric="Share of investees discharging untreated waste water", unit="%", mandatory=False,
        iris_cross_refs=["OI9412", "OI7860"],
        data_points=["Waste water treatment", "Discharge volumes"],
    ),
    # Social optional
    SFDRIndicator(
        number=21, name="Lack of human rights policy", category="social",
        metric="Share of investments without a human rights policy", unit="%", mandatory=False,
        iris_cross_refs=["OI4753", "OI4324"],
        data_points=["Human rights policy", "Due diligence process"],
    ),
    SFDRIndicator(
        number=22, name="Lack of anti-corruption and anti-bribery policy", category="anti-corruption",
        metric="Share of investments without anti-corruption policies", unit="%", mandatory=False,
        iris_cross_refs=["OI4753", "OI4732"],
        data_points=["Anti-corruption policy", "Whistleblower mechanism"],
    ),
    SFDRIndicator(
        number=23, name="Excessive CEO pay ratio", category="social",
        metric="Average ratio of CEO compensation to median employee compensation", mandatory=False,
        iris_cross_refs=["OI1582"],  # Wage equity
        data_points=["CEO total compensation", "Median employee compensation"],
    ),
]


def get_pai_indicators(mandatory_only: bool = True) -> list[SFDRIndicator]:
    if mandatory_only:
        return [i for i in PAI_INDICATORS if i.mandatory]
    return PAI_INDICATORS + OPTIONAL_PAI_INDICATORS


def assess_sfdr_compliance(
    reported_data: dict[str, str] | None = None,
    company_description: str = "",
    document_text: str = "",
    *,
    proxy_data: dict[str, str] | None = None,
    not_applicable: list[str] | set[str] | None = None,
) -> dict:
    """Assess which SFDR PAI indicators a company can report on.

    Text matches are treated as mentions only. Reportable coverage requires
    direct PAI data, proxy data, a mapped IRIS+ metric, or an explicit
    not-applicable reviewer decision.
    """
    import re

    text = f"{company_description} {document_text}".lower()
    reported = {_normalize_reported_key(k): str(v) for k, v in (reported_data or {}).items()}
    proxies = {_normalize_reported_key(k): str(v) for k, v in (proxy_data or {}).items()}
    na = {_normalize_reported_key(v) for v in (not_applicable or [])}

    def _match(t: str, kw: str) -> bool:
        kw = kw.lower()
        if " " in kw or "-" in kw:
            return kw in t
        return bool(re.search(r"\b" + re.escape(kw) + r"\b", t))

    def _reported_pai(number: int) -> bool:
        suffixes = {str(number), f"PAI{number}", f"SFDRPAI{number}"}
        return bool(suffixes & set(reported))

    def _proxy_pai(number: int) -> bool:
        suffixes = {str(number), f"PAI{number}", f"SFDRPAI{number}"}
        return bool(suffixes & set(proxies))

    def _na_pai(number: int) -> bool:
        suffixes = {str(number), f"PAI{number}", f"SFDRPAI{number}"}
        return bool(suffixes & na)

    indicator_keywords = {
        1: ["scope 1", "scope 2", "scope 3", "ghg emission", "greenhouse gas", "carbon emission"],
        2: ["carbon footprint", "portfolio carbon"],
        3: ["ghg intensity", "carbon intensity", "emission intensity"],
        4: ["fossil fuel", "oil", "gas", "coal", "exploration"],
        5: ["non-renewable", "renewable energy", "energy mix"],
        6: ["energy consumption", "energy intensity", "NACE"],
        7: ["biodiversity", "protected area", "natura 2000", "UNESCO"],
        8: ["emissions to water", "water pollution", "effluent"],
        9: ["hazardous waste", "radioactive waste"],
        10: ["UNGC", "UN global compact", "OECD guidelines", "violation"],
        11: ["compliance mechanism", "grievance", "complaint handling"],
        12: ["gender pay gap", "pay equity", "wage gap"],
        13: ["board diversity", "female board", "board gender"],
        14: ["controversial weapons", "cluster munitions", "anti-personnel"],
    }

    result = {
        "framework": "SFDR PAI (14 Mandatory Indicators)",
        "indicators": [],
        "total": 14,
        "addressed": 0,
        "gaps": 0,
        "available": 0,
        "proxy": 0,
        "not_applicable": 0,
        "mentioned": 0,
        "status_counts": {
            "available": 0,
            "proxy": 0,
            "not_applicable": 0,
            "mentioned": 0,
            "missing": 0,
        },
        "assessment_basis": (
            "direct/proxy/explicit-not-applicable coverage; text mentions are "
            "not counted as reportable PAI coverage"
        ),
    }

    for ind in PAI_INDICATORS:
        status: Literal["available", "proxy", "not_applicable", "mentioned", "missing"] = "missing"
        evidence: list[str] = []

        kws = indicator_keywords.get(ind.number, [])
        hits = [kw for kw in kws if _match(text, kw)]
        if len(hits) >= 1:
            status = "mentioned"
            evidence.extend(f"text mention: {hit}" for hit in hits)

        if _na_pai(ind.number):
            status = "not_applicable"
            evidence.append("Marked not applicable by reviewer")

        if _reported_pai(ind.number):
            status = "available"
            evidence.append(f"PAI {ind.number} reported")

        if status not in {"available", "not_applicable"} and _proxy_pai(ind.number):
            status = "proxy"
            evidence.append(f"PAI {ind.number} proxy supplied")

        if status not in {"available", "not_applicable", "proxy"} and ind.iris_cross_refs:
            for ref in ind.iris_cross_refs:
                if ref.upper() in reported:
                    status = "proxy"
                    evidence.append(f"IRIS+ {ref} reported as proxy")
                    break
                if ref.upper() in proxies:
                    status = "proxy"
                    evidence.append(f"IRIS+ {ref} proxy supplied")
                    break

        addressed = status in {"available", "proxy", "not_applicable"}

        ind_result = {
            "number": ind.number,
            "name": ind.name,
            "category": ind.category,
            "status": status,
            "addressed": addressed,
            "evidence": evidence,
            "data_points_needed": ind.data_points if status in {"missing", "mentioned"} else [],
        }
        result["indicators"].append(ind_result)

        result["status_counts"][status] += 1
        if addressed:
            result["addressed"] += 1
            if status in {"available", "proxy", "not_applicable"}:
                result[status] += 1
        else:
            result["gaps"] += 1
            if status == "mentioned":
                result["mentioned"] += 1

    result["coverage_pct"] = round(result["addressed"] / result["total"] * 100, 1)
    return result


def _normalize_reported_key(value: object) -> str:
    import re

    return re.sub(r"[^A-Z0-9]", "", str(value).strip().upper())


# ---------------------------------------------------------------------------
# Article 6 / 8 / 9 Fund Classification
# ---------------------------------------------------------------------------

_ARTICLE_DESCRIPTIONS = {
    6: "No ESG integration commitments (basic risk disclosure only)",
    8: "Promotes E/S characteristics alongside financial return (light green)",
    9: "Sustainable investment as its objective (dark green)",
}


def classify_sfdr_article(
    description: str = "",
    document_text: str = "",
    fund_name: str = "",
    has_sustainability_objective: bool = False,
    pct_sustainable_investments: float | None = None,
) -> SFDRArticleClassification:
    """Classify a fund under SFDR Article 6, 8, or 9.

    Article 9 requires the fund to have sustainable investment as its *objective*
    with measurable targets. Article 8 promotes E/S characteristics without making
    sustainable investment the primary objective. Article 6 is the default.
    """
    text = f"{description} {document_text} {fund_name}".lower()

    art9_signals = [
        "sustainable investment objective", "article 9", "art 9", "dark green",
        "sustainable investment as its objective", "taxonomy-aligned",
    ]
    art8_signals = [
        "promotes environmental", "promotes social", "esg integration",
        "article 8", "art 8", "light green", "e/s characteristics",
        "environmental and social characteristics",
    ]

    art9_hits = [s for s in art9_signals if s in text]
    art8_hits = [s for s in art8_signals if s in text]

    if has_sustainability_objective or art9_hits:
        article = 9
        confidence = "high" if has_sustainability_objective else "medium"
    elif art8_hits or (pct_sustainable_investments is not None and pct_sustainable_investments > 0):
        article = 8
        confidence = "high" if len(art8_hits) >= 2 else "medium"
    else:
        article = 6
        confidence = "high" if not art8_hits and not art9_hits else "low"

    requirements: list[str] = []
    if article == 9:
        requirements = [
            "Disclose how the sustainable investment objective is achieved",
            "Show that investments do no significant harm (DNSH) to other E/S objectives",
            "Report on all 14 mandatory PAI indicators",
            "Disclose proportion of investments aligned with EU Taxonomy",
            "Pre-contractual and periodic disclosures per Annex III/V",
        ]
    elif article == 8:
        requirements = [
            "Disclose how E/S characteristics are promoted",
            "Report on relevant PAI indicators (at minimum those related to promoted characteristics)",
            "If making sustainable investments, apply DNSH criteria",
            "Pre-contractual and periodic disclosures per Annex II/IV",
        ]
    else:
        requirements = [
            "Disclose how sustainability risks are integrated into investment decisions",
            "State whether PAI is considered (comply or explain)",
        ]

    return SFDRArticleClassification(
        article=article,
        description=_ARTICLE_DESCRIPTIONS[article],
        confidence=confidence,
        evidence=art9_hits or art8_hits or [],
        requirements=requirements,
        pct_sustainable_investments=pct_sustainable_investments,
    )


# ---------------------------------------------------------------------------
# SFDR 2.0 category preview (proposed law — NOT in force)
#
# The Commission's 2025-11-20 recast replaces the Article 6/8/9 split with
# three voluntary product categories, each requiring >=70% of the portfolio to
# follow the relevant strategy plus mandatory exclusions. The Council's
# negotiating position (2026-06-24) keeps the categories and adds flexibility
# the classifier below models as toggles: a phase-in for the 70% threshold
# while a fund deploys capital, and permitted deviations for delayed
# divestment from illiquid assets. Trilogue starts late 2026; application is
# not expected before ~2029. Until then Article 6/8/9 remains the law.
# ---------------------------------------------------------------------------

SFDR2_STATUS_NOTE = (
    "SFDR 2.0 is PROPOSED LAW, not in force (Council position 2026-06-24; "
    "trilogue from late 2026; application expected ~2029 after a 24-month "
    "implementation period). Classify against Article 6/8/9 for current "
    "compliance; use this preview to plan label migration."
)

SFDR2_CATEGORY_DESCRIPTIONS: dict[str, str] = {
    "sustainable": (
        "Sustainable (revised Art 9): invests in economic activities that are "
        "already environmentally or socially sustainable."
    ),
    "transition": (
        "Transition (new Art 7): invests in assets on a credible improvement "
        "pathway — transition plans, science-based targets, measurable progress."
    ),
    "esg_basics": (
        "ESG Basics (new Art 8): applies binding ESG selection criteria without "
        "claiming sustainability or transition outcomes."
    ),
    "unclassified": (
        "Unclassified: no category claimed — analogous to today's Article 6 "
        "(categories are voluntary under the proposal)."
    ),
}

_SFDR2_THRESHOLD_PCT = 70.0


class SFDR2Input(BaseModel):
    """Structured inputs for the SFDR 2.0 category preview."""

    description: str = ""
    document_text: str = ""
    current_article: int | None = Field(
        default=None, description="Current SFDR classification (6, 8, or 9) if known"
    )
    has_sustainable_objective: bool = False
    has_transition_plan: bool = Field(
        default=False,
        description="Portfolio assets follow credible transition plans / science-based targets",
    )
    applies_binding_esg_criteria: bool = False
    pct_strategy_aligned: float | None = Field(
        default=None, ge=0, le=100,
        description="% of portfolio following the category's ESG strategy (>=70% required)",
    )
    invests_in_controversial_weapons: bool = False
    invests_in_tobacco_production: bool = False
    has_ungc_oecd_violators: bool = False
    coal_revenue_pct_max: float | None = Field(
        default=None, ge=0, le=100,
        description="Highest coal-revenue share among holdings, if known",
    )
    fund_in_ramp_up: bool = Field(
        default=False,
        description="Fund is still deploying capital (Council phase-in relief candidate)",
    )
    illiquid_divestment_pending: bool = Field(
        default=False,
        description="Below-threshold due to pending divestment of illiquid assets (Council deviation candidate)",
    )
    apply_council_flexibility: bool = Field(
        default=True,
        description="Model the Council-position phase-in / illiquid-asset deviations",
    )


class SFDR2Classification(BaseModel):
    """SFDR 2.0 category preview result."""

    category: Literal["sustainable", "transition", "esg_basics", "unclassified"]
    description: str = ""
    status: str = SFDR2_STATUS_NOTE
    threshold_required_pct: float = _SFDR2_THRESHOLD_PCT
    threshold_met: bool | None = None
    exclusion_flags: list[str] = Field(default_factory=list)
    migration_note: str = ""
    rationale: list[str] = Field(default_factory=list)
    caveats: list[str] = Field(default_factory=list)


_ARTICLE_TO_SFDR2: dict[int, tuple[str, str]] = {
    9: ("sustainable", "Art 9 funds are the natural candidates for the Sustainable category, but must re-evidence the 70% threshold and mandatory exclusions."),
    8: ("esg_basics", "Art 8 funds map to ESG Basics by default; those holding credible transition-plan assets may instead target the Transition category."),
    6: ("unclassified", "Art 6 funds remain unclassified unless they adopt one of the voluntary categories."),
}


def classify_sfdr2_category(input: SFDR2Input) -> SFDR2Classification:  # noqa: A002
    """Preview which SFDR 2.0 category a fund could claim (proposed law).

    Deterministic screen: category candidate from objectives / transition
    plans / binding criteria (falling back to the Art 6/8/9 migration map),
    the >=70% strategy-alignment threshold, and the mandatory-exclusion flags
    shared by all three categories. Council-position flexibility (threshold
    phase-in during ramp-up, delayed divestment of illiquid assets) is
    modelled as caveats, not as a pass.
    """
    text = f"{input.description} {input.document_text}".lower()
    rationale: list[str] = []

    # --- category candidate -------------------------------------------------
    transition_signals = input.has_transition_plan or any(
        term in text for term in ("transition plan", "science-based target", "sbti", "decarbonisation pathway", "decarbonization pathway")
    )
    if input.has_sustainable_objective or input.current_article == 9:
        category = "sustainable"
        rationale.append("Sustainable-investment objective (or current Art 9 status) → Sustainable candidate.")
    elif transition_signals:
        category = "transition"
        rationale.append("Credible transition-plan / science-based-target signals → Transition candidate.")
    elif input.applies_binding_esg_criteria or input.current_article == 8:
        category = "esg_basics"
        rationale.append("Binding ESG selection criteria (or current Art 8 status) → ESG Basics candidate.")
    else:
        category = "unclassified"
        rationale.append("No category-qualifying strategy found — categories are voluntary; fund stays unclassified.")

    # --- 70% threshold --------------------------------------------------------
    caveats: list[str] = []
    threshold_met: bool | None = None
    if category != "unclassified":
        if input.pct_strategy_aligned is None:
            caveats.append(
                "pct_strategy_aligned not supplied — the >=70% portfolio-alignment "
                "threshold could not be checked."
            )
        else:
            threshold_met = input.pct_strategy_aligned >= _SFDR2_THRESHOLD_PCT
            rationale.append(
                f"Strategy alignment {input.pct_strategy_aligned:.0f}% vs >=70% required → "
                + ("met." if threshold_met else "NOT met.")
            )
            if not threshold_met and input.apply_council_flexibility:
                if input.fund_in_ramp_up:
                    caveats.append(
                        "Council position: the Commission may set phase-in rules for "
                        "funds still deploying capital — the shortfall may be tolerated "
                        "during ramp-up (delegated act pending)."
                    )
                if input.illiquid_divestment_pending:
                    caveats.append(
                        "Council position: limited deviations may be permitted for "
                        "delayed divestment from illiquid assets (delegated act pending)."
                    )

    # --- mandatory exclusions -------------------------------------------------
    exclusion_flags: list[str] = []
    if input.invests_in_controversial_weapons:
        exclusion_flags.append("Controversial weapons exposure — excluded in every SFDR 2.0 category.")
    if input.invests_in_tobacco_production:
        exclusion_flags.append("Tobacco production exposure — excluded in every SFDR 2.0 category.")
    if input.has_ungc_oecd_violators:
        exclusion_flags.append("UNGC / OECD Guidelines violators in portfolio — excluded in every SFDR 2.0 category.")
    if input.coal_revenue_pct_max is not None and input.coal_revenue_pct_max > 0 and category in ("sustainable", "transition"):
        exclusion_flags.append(
            f"Coal revenue exposure up to {input.coal_revenue_pct_max:.0f}% — check the "
            "category-specific coal-revenue threshold in the final text."
        )
    if exclusion_flags and category != "unclassified":
        rationale.append("Mandatory-exclusion breaches would disqualify the category claim until resolved.")

    migration_note = ""
    if input.current_article in _ARTICLE_TO_SFDR2:
        migration_note = _ARTICLE_TO_SFDR2[input.current_article][1]

    return SFDR2Classification(
        category=category,
        description=SFDR2_CATEGORY_DESCRIPTIONS[category],
        threshold_met=threshold_met,
        exclusion_flags=exclusion_flags,
        migration_note=migration_note,
        rationale=rationale,
        caveats=caveats,
    )


def assess_sfdr_entity_vs_fund(
    entity_description: str = "",
    fund_descriptions: list[dict[str, str]] | None = None,
) -> dict:
    """Distinguish entity-level vs product-level SFDR obligations.

    Entity-level: applies to the financial market participant as a whole.
    Product-level: applies per fund/product under management.
    """
    entity_obligations = [
        "Publish principal adverse impact statement (Art. 4) or explain why not",
        "Disclose sustainability risk integration policy (Art. 3)",
        "Disclose remuneration policy consistency with sustainability risk integration (Art. 5)",
    ]

    fund_results: list[dict] = []
    for fund in (fund_descriptions or []):
        cls = classify_sfdr_article(
            description=fund.get("description", ""),
            fund_name=fund.get("name", ""),
        )
        fund_results.append({"name": fund.get("name", ""), **cls.model_dump()})

    return {
        "entity_level": {
            "obligations": entity_obligations,
            "applies_to": "Financial Market Participant (firm-wide)",
        },
        "product_level": {
            "funds_classified": len(fund_results),
            "funds": fund_results,
        },
    }
