"""Consultant engagement workspace (v4 — Tracks 1-10).

v4's "integration wave" entry point. The :mod:`impact.engagements` package
wraps the v3 institutional-readiness backbone into the consultant workflow
described in ``docs/roadmap-v4.md``:

* :mod:`~openharness.impact.engagements.models` — canonical data contracts.
* :mod:`~openharness.impact.engagements.bundles` — 12 productised engagement
  bundles from §4a.
* :mod:`~openharness.impact.engagements.checklist` — consultant checklist
  generator (Discovery → Training).
* :mod:`~openharness.impact.engagements.proposal` — proposal builder.
* :mod:`~openharness.impact.engagements.templates` — client-type templates.
* :mod:`~openharness.impact.engagements.workspace` — in-memory workspace +
  audit trail integration.
* :mod:`~openharness.impact.engagements.toc_builder` — Theory of Change
  canvas, logic validator, multi-framework KPI generator (Track 2).
* :mod:`~openharness.impact.engagements.data_room` — data request packs,
  evidence completeness, exception workflow, coaching cards (Track 3).
* :mod:`~openharness.impact.engagements.value_creation` — benchmarks, risk
  rating, value-creation plan, business case, scenarios, supply chain
  (Track 4).
* :mod:`~openharness.impact.engagements.reporting_studio` — multi-audience
  report builder, claim review panel, executive deck, public microsite
  (Track 5).
* :mod:`~openharness.impact.engagements.training` — training-plan
  generator, workshop packs, coaching cards, learning loop, readiness
  badges (Track 6).
* :mod:`~openharness.impact.engagements.website` — diagnostic quiz, report
  gallery, benchmark teaser, playbook library, lead capture, upload demo,
  partner mode (Track 7).
* :mod:`~openharness.impact.engagements.copilot` — AI consultant copilot
  governance scaffolding, challenge mode, client-safe answer mode,
  meeting-note ingestion (Track 8).
* :mod:`~openharness.impact.engagements.regulatory` — jurisdiction wizard,
  SFDR classification, UK SDR labels, deadline calendar, regulator
  narrative (Track 9).
* :mod:`~openharness.impact.engagements.verification_bundle` — BlueMark-style
  3-pillar verification bundle (Mandate + Practice + Reporting), verifier
  token, marketplace metadata, signed assurance manifest, readiness badge
  (Track 10).

Engineering note: per roadmap-v4 §4 the :mod:`engagements` package must
**never** fork an existing v3 module. Every capability is referenced by ID
and wired together in :class:`EngagementWorkspace`.
"""

from __future__ import annotations

from openharness.impact.engagements.bundles import (
    EngagementBundle,
    EngagementBundleType,
    ENGAGEMENT_BUNDLES,
    get_bundle,
    list_bundles,
)
from openharness.impact.engagements.checklist import (
    CONSULTANT_CHECKLIST_PHASES,
    ChecklistPhase,
    build_consultant_checklist,
)
from openharness.impact.engagements.copilot import (
    ChallengeFinding,
    CopilotAnswer,
    CopilotOutput,
    CopilotReviewQueue,
    EngagementQuery,
    MeetingNoteIngestion,
    answer_from_approved_evidence,
    extract_meeting_notes,
    run_challenge,
)
from openharness.impact.engagements.data_room import (
    CoachingCard,
    CompletenessReport,
    CompletenessRow,
    DataQualityException,
    DataRequestField,
    DataRequestPack,
    DataRoomSubmission,
    FieldSubmission,
    MultiEntityRollup,
    build_coaching_cards,
    build_data_request_pack,
    rollup_multi_entity,
    score_completeness,
)
from openharness.impact.engagements.models import (
    ClientType,
    DeliverableState,
    ChecklistItem,
    ChecklistStatus,
    ConsultantOverride,
    Deliverable,
    Engagement,
    EngagementDecision,
    EngagementDocument,
    EngagementNote,
    EngagementStatus,
    TemplateLibraryEntry,
)
from openharness.impact.engagements.proposal import (
    EngagementProposal,
    ProposalAssumption,
    ProposalFeeLine,
    ProposalRiskCaveat,
    ProposalWorkplanItem,
    build_proposal,
)
from openharness.impact.engagements.regulatory import (
    JURISDICTION_PROFILES,
    Jurisdiction,
    RegulatoryJurisdictionProfile,
    RegulatorNarrative,
    RegulatoryDeadline,
    RegulatoryObligation,
    SFDRClassificationInput,
    SFDRClassificationResult,
    UKSDRLabelInput,
    UKSDRLabelResult,
    build_regulator_narrative,
    classify_sfdr,
    classify_uk_sdr,
    get_jurisdiction_profile,
    list_jurisdictions,
    schedule_deadlines,
)
from openharness.impact.engagements.reporting_studio import (
    AUDIENCE_HINTS,
    Audience,
    ApprovalState,
    ClaimReview,
    ClaimStatus,
    DeckSlide,
    EvidenceDepth,
    ExecutiveDeckOutline,
    MultiAudienceRewrite,
    PublicMicrositeBundle,
    PublicMicrositePage,
    REPORT_TEMPLATES,
    Report,
    ReportSection,
    ReportTemplate,
    build_executive_deck,
    build_public_microsite,
    build_report_from_template,
    decide_claim,
    get_report_template,
    list_report_templates,
    rewrite_for_audiences,
    transition_report,
)
from openharness.impact.engagements.templates import (
    CLIENT_TEMPLATE_LIBRARY,
    get_client_template,
)
from openharness.impact.engagements.toc_builder import (
    KPIFramework,
    KPIFrameworkEntry,
    ToCAssumption,
    ToCCanvas,
    ToCCanvasEdge,
    ToCCanvasNode,
    ToCNodeKind,
    ToCRisk,
    ToCValidationFinding,
    ToCValidationReport,
    draft_toc_from_intake,
    generate_kpi_framework,
    lock_kpi_framework,
    render_canvas_markdown,
    render_canvas_mermaid,
    validate_toc_canvas,
)
from openharness.impact.engagements.training import (
    InvesteeCoachingCard,
    LearningLoopEntry,
    MaturityStage,
    ReadinessBadge,
    TrainingAction,
    TrainingPlan,
    WORKSHOP_PACKS,
    WorkshopPack,
    build_coaching_card,
    build_training_plan,
    get_workshop_pack,
    issue_readiness_badge,
    list_workshop_packs,
    record_learning_loop,
)
from openharness.impact.engagements.value_creation import (
    BenchmarkObservation,
    BenchmarkProvider,
    BenchmarkQuery,
    BenchmarkResult,
    BusinessCase,
    ImpactRiskEntry,
    ImpactRiskRating,
    InMemoryBenchmarkProvider,
    PeerDashboard,
    RiskCategory,
    ScenarioInput,
    ScenarioOutcome,
    ScenarioResult,
    SupplyChainHotspot,
    ValueCreationAction,
    ValueCreationPlan,
    build_business_case,
    build_peer_dashboard,
    build_risk_rating,
    build_value_creation_plan,
    get_default_benchmark_provider,
    run_scenario,
    score_supply_chain_hotspots,
    set_default_benchmark_provider,
)
from openharness.impact.engagements.verification_bundle import (
    AssuranceBundle,
    AssuranceManifest,
    AssuranceReadinessBadge,
    MandateItem,
    MandatePack,
    PracticePack,
    PracticePrincipleItem,
    ReportingClaim,
    ReportingPack,
    VERIFIER_MARKETPLACE,
    VerifierMarketplaceListing,
    VerifierToken,
    build_assurance_bundle,
    build_mandate_pack,
    build_practice_pack,
    build_reporting_pack,
    evaluate_assurance_readiness,
    issue_verifier_token,
    list_verifier_marketplace,
    verify_assurance_bundle,
)
from openharness.impact.engagements.website import (
    BenchmarkTeaser,
    BenchmarkTeaserRow,
    DIAGNOSTIC_QUESTIONS,
    DiagnosticAnswer,
    DiagnosticQuestion,
    DiagnosticResult,
    GalleryItem,
    LeadCapture,
    PLAYBOOK_PAGES,
    PartnerMode,
    PlaybookPage,
    REPORT_GALLERY,
    UploadDemoResult,
    build_benchmark_teaser,
    capture_lead,
    describe_partner_mode,
    get_playbook_page,
    list_diagnostic_questions,
    list_gallery_items,
    list_playbook_pages,
    run_upload_demo,
    score_diagnostic,
)
from openharness.impact.engagements.workspace import (
    EngagementWorkspace,
    EngagementWorkspaceSummary,
)

__all__ = [
    # core workspace (Track 1)
    "CLIENT_TEMPLATE_LIBRARY",
    "CONSULTANT_CHECKLIST_PHASES",
    "ChecklistItem",
    "ChecklistPhase",
    "ChecklistStatus",
    "ClientType",
    "ConsultantOverride",
    "Deliverable",
    "DeliverableState",
    "ENGAGEMENT_BUNDLES",
    "Engagement",
    "EngagementBundle",
    "EngagementBundleType",
    "EngagementDecision",
    "EngagementDocument",
    "EngagementNote",
    "EngagementProposal",
    "EngagementStatus",
    "EngagementWorkspace",
    "EngagementWorkspaceSummary",
    "ProposalAssumption",
    "ProposalFeeLine",
    "ProposalRiskCaveat",
    "ProposalWorkplanItem",
    "TemplateLibraryEntry",
    "build_consultant_checklist",
    "build_proposal",
    "get_bundle",
    "get_client_template",
    "list_bundles",
    # Track 2: ToC + KPI framework
    "KPIFramework",
    "KPIFrameworkEntry",
    "ToCAssumption",
    "ToCCanvas",
    "ToCCanvasEdge",
    "ToCCanvasNode",
    "ToCNodeKind",
    "ToCRisk",
    "ToCValidationFinding",
    "ToCValidationReport",
    "draft_toc_from_intake",
    "generate_kpi_framework",
    "lock_kpi_framework",
    "render_canvas_markdown",
    "render_canvas_mermaid",
    "validate_toc_canvas",
    # Track 3: data room
    "CoachingCard",
    "CompletenessReport",
    "CompletenessRow",
    "DataQualityException",
    "DataRequestField",
    "DataRequestPack",
    "DataRoomSubmission",
    "FieldSubmission",
    "MultiEntityRollup",
    "build_coaching_cards",
    "build_data_request_pack",
    "rollup_multi_entity",
    "score_completeness",
    # Track 4: value creation intelligence
    "BenchmarkObservation",
    "BenchmarkProvider",
    "BenchmarkQuery",
    "BenchmarkResult",
    "BusinessCase",
    "ImpactRiskEntry",
    "ImpactRiskRating",
    "InMemoryBenchmarkProvider",
    "PeerDashboard",
    "RiskCategory",
    "ScenarioInput",
    "ScenarioOutcome",
    "ScenarioResult",
    "SupplyChainHotspot",
    "ValueCreationAction",
    "ValueCreationPlan",
    "build_business_case",
    "build_peer_dashboard",
    "build_risk_rating",
    "build_value_creation_plan",
    "get_default_benchmark_provider",
    "run_scenario",
    "score_supply_chain_hotspots",
    "set_default_benchmark_provider",
    # Track 5: reporting studio
    "AUDIENCE_HINTS",
    "ApprovalState",
    "Audience",
    "ClaimReview",
    "ClaimStatus",
    "DeckSlide",
    "EvidenceDepth",
    "ExecutiveDeckOutline",
    "MultiAudienceRewrite",
    "PublicMicrositeBundle",
    "PublicMicrositePage",
    "REPORT_TEMPLATES",
    "Report",
    "ReportSection",
    "ReportTemplate",
    "build_executive_deck",
    "build_public_microsite",
    "build_report_from_template",
    "decide_claim",
    "get_report_template",
    "list_report_templates",
    "rewrite_for_audiences",
    "transition_report",
    # Track 6: training & capacity
    "InvesteeCoachingCard",
    "LearningLoopEntry",
    "MaturityStage",
    "ReadinessBadge",
    "TrainingAction",
    "TrainingPlan",
    "WORKSHOP_PACKS",
    "WorkshopPack",
    "build_coaching_card",
    "build_training_plan",
    "get_workshop_pack",
    "issue_readiness_badge",
    "list_workshop_packs",
    "record_learning_loop",
    # Track 7: website productisation
    "BenchmarkTeaser",
    "BenchmarkTeaserRow",
    "DIAGNOSTIC_QUESTIONS",
    "DiagnosticAnswer",
    "DiagnosticQuestion",
    "DiagnosticResult",
    "GalleryItem",
    "LeadCapture",
    "PLAYBOOK_PAGES",
    "PartnerMode",
    "PlaybookPage",
    "REPORT_GALLERY",
    "UploadDemoResult",
    "build_benchmark_teaser",
    "capture_lead",
    "describe_partner_mode",
    "get_playbook_page",
    "list_diagnostic_questions",
    "list_gallery_items",
    "list_playbook_pages",
    "run_upload_demo",
    "score_diagnostic",
    # Track 8: AI consultant copilot
    "ChallengeFinding",
    "CopilotAnswer",
    "CopilotOutput",
    "CopilotReviewQueue",
    "EngagementQuery",
    "MeetingNoteIngestion",
    "answer_from_approved_evidence",
    "extract_meeting_notes",
    "run_challenge",
    # Track 9: regulatory workbench
    "JURISDICTION_PROFILES",
    "Jurisdiction",
    "RegulatoryJurisdictionProfile",
    "RegulatorNarrative",
    "RegulatoryDeadline",
    "RegulatoryObligation",
    "SFDRClassificationInput",
    "SFDRClassificationResult",
    "UKSDRLabelInput",
    "UKSDRLabelResult",
    "build_regulator_narrative",
    "classify_sfdr",
    "classify_uk_sdr",
    "get_jurisdiction_profile",
    "list_jurisdictions",
    "schedule_deadlines",
    # Track 10: verification bundle
    "AssuranceBundle",
    "AssuranceManifest",
    "AssuranceReadinessBadge",
    "MandateItem",
    "MandatePack",
    "PracticePack",
    "PracticePrincipleItem",
    "ReportingClaim",
    "ReportingPack",
    "VERIFIER_MARKETPLACE",
    "VerifierMarketplaceListing",
    "VerifierToken",
    "build_assurance_bundle",
    "build_mandate_pack",
    "build_practice_pack",
    "build_reporting_pack",
    "evaluate_assurance_readiness",
    "issue_verifier_token",
    "list_verifier_marketplace",
    "verify_assurance_bundle",
]
