#!/usr/bin/env python3
"""Generate docs/reference/tools.md and the code facts the docs quote (v7 W5.7).

    python scripts/build_tool_reference.py          # write docs/reference/tools.md
    python scripts/build_tool_reference.py --check  # exit 1 if it is out of date

``code_facts()`` is also used by tests/test_docs_counts.py, which fails when
README.md / CLAUDE.md quote a number that no longer matches the code.
"""

from __future__ import annotations

import argparse
import pkgutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
OUT = ROOT / "docs" / "reference" / "tools.md"


def impact_tools() -> list:
    from impact_vision.tools import create_default_tool_registry

    return sorted(
        (
            tool
            for tool in create_default_tool_registry().list_tools()
            if type(tool).__module__.startswith("impact_vision.tools.impact.")
            and not getattr(tool, "deprecated_for", None)
        ),
        key=lambda tool: tool.name,
    )


def code_facts() -> dict[str, int]:
    import impact_vision.impact.frameworks as frameworks
    from impact_vision.impact.benchmarks import SECTOR_BENCHMARKS
    from impact_vision.impact.dd_checklist import load_checklist
    from impact_vision.impact.engagements.regulatory import JURISDICTION_PROFILES
    from impact_vision.impact.frameworks.cross_reference import CROSS_REFERENCE_MAP
    from impact_vision.tools.impact.engagement_suite_catalog import ACTION_AREAS

    questions = load_checklist()
    framework_modules = [
        m.name for m in pkgutil.iter_modules(frameworks.__path__)
        if m.name not in {"cross_reference", "sfdr_v2"}  # crosswalk + deprecated shim
    ]
    return {
        "impact_tools": len(impact_tools()),
        "suite_actions": len({a for actions in ACTION_AREAS.values() for a in actions}),
        "crosswalk_concepts": len(CROSS_REFERENCE_MAP),
        "jurisdiction_profiles": len(JURISDICTION_PROFILES),
        "sector_benchmarks": len(SECTOR_BENCHMARKS),
        "dd_questions": len(questions),
        "dd_categories": len({q.category for q in questions}),
        "framework_modules": len(framework_modules),
    }


def render() -> str:
    facts = code_facts()
    lines = [
        "# Tool reference",
        "",
        "<!-- Generated by scripts/build_tool_reference.py — do not edit by hand. -->",
        "",
        f"Impact Vision registers **{facts['impact_tools']} impact agent tools**. The same registry",
        "feeds the CLI, REST (`/api/v1/tools`), MCP and the web console, so this list is",
        "what every surface exposes.",
        "",
        "## Counts quoted in the docs",
        "",
        "| Fact | Value |",
        "|------|-------|",
    ]
    labels = {
        "impact_tools": "Impact agent tools",
        "suite_actions": "`engagement_suite` actions",
        "crosswalk_concepts": "Cross-framework concepts (`cross_reference`)",
        "jurisdiction_profiles": "Regulatory jurisdiction profiles",
        "sector_benchmarks": "Sector benchmarks",
        "dd_questions": "DD checklist questions",
        "dd_categories": "DD checklist categories",
        "framework_modules": "Framework modules (`impact/frameworks/`)",
    }
    lines += [f"| {labels[k]} | {v} |" for k, v in facts.items()]
    lines += ["", "## Tools", "", "| Tool | Description |", "|------|-------------|"]
    for tool in impact_tools():
        description = " ".join(tool.description.split()).replace("|", "\\|")
        lines.append(f"| `{tool.name}` | {description} |")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    text = render()
    if args.check:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != text:
            print(f"{OUT.relative_to(ROOT)} is out of date: run python scripts/build_tool_reference.py")
            return 1
        print(f"{OUT.relative_to(ROOT)} is up to date")
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
