"""User-facing strings for the decision report (v7 W2.1 / W2.5).

Every visible label goes through :func:`translator` so a language is just a
dictionary. Missing keys fall back to English, so a partial translation never
breaks a report.
"""

from __future__ import annotations

from collections.abc import Callable

EN: dict[str, str] = {
    "doc_title": "Impact assessment",
    "eyebrow": "Impact assessment",
    "generated": "Generated {date}",
    "standard": "IRIS+ {version}",
    "source": "Source: {source}",
    "skip": "Skip to report",
    "contents": "Contents",
    "notice_full": "Confidential — prepared for internal investment and LP use.",
    "notice_ic": "Confidential — prepared for the investment committee.",
    "notice_lp": "Confidential — prepared for the fund's limited partners.",
    "notice_regulator": "Prepared for regulatory review.",
    "notice_public": "Prepared for public disclosure.",
    # verdict
    "sec_verdict": "Recommendation",
    "verdict_pass": "Proceed to investment committee",
    "verdict_warn": "Conditional — resolve before IC",
    "verdict_insufficient": "Not IC-ready — insufficient evidence",
    "verdict_fail": "Do not proceed",
    "verdict_unknown": "No IC gate run",
    "why": "Why",
    "missing_data": "missing data",
    "confidence_evidence-based": "Confidence: scores rest on reported metrics.",
    "confidence_partial": "Confidence: partly evidenced — some scores rest on a few reported metrics.",
    "confidence_estimated": "Confidence: estimated from document text only — treat as a hypothesis.",
    # kpis
    "kpi_5d": "5 Dimensions score",
    "kpi_5d_sub": "Grade {grade} · {evidence}",
    "kpi_sdg": "Top SDG",
    "kpi_sdg_none": "None material",
    "kpi_gw": "Greenwashing risk",
    "kpi_evidence": "Evidence",
    "kpi_evidence_value": "{claims} claims",
    "kpi_evidence_sub": "{metrics} IRIS+ metrics · DD {dd}% covered",
    "kpi_evidence_sub_nodd": "{metrics} IRIS+ metrics",
    "evidence-based": "evidence-based",
    "partial": "partial evidence",
    "estimated": "estimated",
    # change our mind
    "sec_mind": "What would change our mind",
    "lede_mind": "The three pieces of evidence that would move this assessment most.",
    "mind_metric": "Report {name} ({id})",
    "mind_metric_why": "{dimension} is the weakest dimension ({score}/5, {evidence}); this is a core metric for the sector.",
    "mind_verify": "Independent verification of the headline claims",
    "mind_verify_why": "No third-party verification or audit was found for the main outcomes.",
    "mind_outcome": "Outcome evidence with a baseline or comparison group",
    "mind_outcome_why": "Most claims show change but not attribution (NESTA level 2); a comparison moves them to level 3.",
    "mind_adverse": "Negative-impact metrics for the sector",
    "mind_adverse_why": "Only positive metrics are reported; omissions raise greenwashing risk.",
    "mind_dd": "Answer: {question}",
    "mind_dd_why": "High-priority due-diligence question not answered by the documents.",
    # 5D
    "sec_5d": "Five Dimensions of Impact",
    "lede_5d": "Scored 1–5. The tick shows the sector benchmark where one exists.",
    "dim_what": "What",
    "dim_who": "Who",
    "dim_how_much": "How much",
    "dim_contribution": "Contribution",
    "dim_risk": "Risk",
    "legend_score": "Company score",
    "legend_bench": "Sector benchmark",
    "table_view": "Show as table",
    "col_dimension": "Dimension",
    "col_score": "Score",
    "col_benchmark": "Benchmark",
    "col_evidence": "Evidence",
    "col_notes": "Notes",
    # SDG
    "sec_sdg": "SDG alignment",
    "lede_sdg": "Material goals only (claimed, inferred from the business, or evidenced by a goal-specific metric), scored 0–100.",
    "sdg_other": "Other goals (context only): {goals}",
    "sdg_none": "No goal is material yet — report goal-specific IRIS+ metrics.",
    "col_goal": "Goal",
    "col_confidence": "Confidence",
    "col_metrics": "Matched metrics",
    # evidence
    "sec_evidence": "Evidence ledger",
    "lede_evidence": "Every claim found in the documents and every metric used in scoring.",
    "col_claim": "Claim",
    "col_type": "Type",
    "col_level": "NESTA level",
    "col_signals": "Evidence",
    "col_metric": "Metric",
    "col_value": "Value",
    "col_origin": "Origin",
    "origin_reported": "reported",
    "origin_extracted": "extracted from text",
    "origin_derived": "derived",
    "claims_caption": "Claims ({n})",
    "metrics_caption": "Metrics ({n})",
    "no_claims": "No claims were extracted.",
    "signal_third_party_verified": "Third-party verified",
    "signal_audited": "Audited",
    "signal_certified": "Certified",
    "signal_controlled_evaluation": "Controlled evaluation",
    "signal_baseline_comparison": "Baseline comparison",
    # greenwashing
    "sec_gw": "Greenwashing review",
    "lede_gw": "Components of the 0–100 risk score. At 60 or above risk is a finding; below it mostly reflects missing data.",
    "gw_claim_metric_gap": "Claims without metrics",
    "gw_adverse_omission": "Missing negative impacts",
    "gw_specificity": "Vague language",
    "gw_selectivity": "Selective reporting",
    "gw_verification": "No verification",
    "legend_component": "Risk component (0–100)",
    "legend_threshold": "Finding threshold (60)",
    "flags": "Flags",
    # risks & actions
    "sec_risks": "Risks and opportunities",
    "risks_disclosed": "Disclosed in the documents",
    "risks_sector": "Typical for the sector — check in diligence",
    "opportunities": "Opportunities",
    "sec_actions": "Action plan",
    "lede_actions": "De-duplicated next steps, most important first.",
    "area_metrics": "Metrics",
    "area_evidence": "Evidence",
    "area_sdg": "SDGs",
    "area_risk": "Risk",
    "area_evidence_quality": "Evidence quality",
    "area_5d": "Impact",
    # targets / feedback
    "sec_targets": "Impact targets",
    "col_target": "Target",
    "col_current": "Current",
    "col_status": "Status",
    "sec_feedback": "Beneficiary feedback",
    # appendix
    "sec_appendix": "Methodology and definitions",
    "method_title": "How this report was produced",
    "method_1": "Claims are extracted from the documents and graded on the NESTA standards of evidence; quantities are mapped to IRIS+ metric IDs only when unit and context are unambiguous.",
    "method_2": "Five Dimensions scores (1–5) come from reported metrics where available and from document text otherwise; the evidence label says which.",
    "method_3": "SDG scores (0–100) combine goal-specific metric coverage, inference from the business and impact themes; cross-cutting metrics count at reduced weight.",
    "method_4": "Greenwashing risk weights claim–metric gaps (30%), missing negative impacts (20%), vague language (20%), selective reporting (15%) and lack of verification (15%).",
    "method_5": "The IC gate applies the fund thesis thresholds; failures caused by missing data are reported as insufficient evidence, not as a negative finding.",
    "glossary_title": "Terms used in this report",
    "kpis_label": "Headline numbers",
    "col_area": "Area",
    "fb_satisfaction": "Satisfaction",
    "fb_nps": "Net Promoter Score",
    "fb_respondents": "Respondents",
    "conf_high": "high confidence",
    "conf_medium": "medium confidence",
    "conf_low": "low confidence",
    "rec_pass": "All gates passed — eligible for IC submission.",
    "rec_warn": "Address the warnings before final approval.",
    "rec_insufficient": "The failed checks reflect missing evidence, not negative findings. Collect the missing metrics and DD answers, then re-screen.",
    "rec_fail": "Resolve the blocking failures and re-screen before IC.",
    "check_5D overall score": "5D overall score",
    "check_Top SDG score": "Top SDG score",
    "check_DD checklist coverage": "DD checklist coverage",
    "check_Greenwashing risk": "Greenwashing risk",
    "check_Exclusion screening": "Exclusion screening",
    "check_Forbidden sector check": "Forbidden sector",
    "check_Required sector check": "Required sector",
    "bound_min": "min",
    "bound_max": "max",
    "gwc_Genuine Impact Leader": "Genuine impact leader",
    "gwc_Substantive with Gaps": "Substantive with gaps",
    "gwc_Moderate Risk": "Moderate risk",
    "gwc_High Risk": "High risk",
    "gwc_Probable Greenwashing": "Probable greenwashing",
    "lang_note": "",
    "generated_by": "Generated by Impact Vision — open-source impact measurement.",
    'sec_glance': 'Impact at a glance',
    'lede_glance': "Material SDGs and how the company's activities lead to outcomes, from the claims in the documents.",
    'wheel_center': 'material goals',
    'stage_activities': 'What they do',
    'stage_outputs': 'Outputs',
    'stage_outcomes': 'Outcomes',
    'stage_targets': 'Targets',
    'stage_empty': 'Nothing reported yet',
    'pill_pass': 'Proceed',
    'pill_warn': 'Conditional',
    'pill_insufficient': 'Not IC-ready',
    'pill_fail': 'Do not proceed',
    'tile_threshold': 'finding threshold 60',
    'mix_legend': 'Claims by NESTA evidence level (1→5)',
}

ZH_HK: dict[str, str] = {
    'doc_title': '影響評估',
    'eyebrow': '影響評估',
    'generated': '生成日期 {date}',
    'standard': 'IRIS+ {version}',
    'source': '來源：{source}',
    'skip': '跳至報告',
    'contents': '目錄',
    'notice_full': '機密——供內部投資及有限合夥人使用。',
    'notice_ic': '機密——供投資委員會使用。',
    'notice_lp': '機密——供基金有限合夥人使用。',
    'notice_regulator': '供監管審閱。',
    'notice_public': '供公開披露。',
    'sec_verdict': '建議',
    'verdict_pass': '可提交投資委員會',
    'verdict_warn': '有條件——提交投資委員會前須處理',
    'verdict_insufficient': '未可提交投資委員會——證據不足',
    'verdict_fail': '不建議推進',
    'verdict_unknown': '未執行投資委員會關卡',
    'why': '原因',
    'missing_data': '資料缺失',
    'confidence_evidence-based': '可信度：評分以已報告指標為依據。',
    'confidence_partial': '可信度：部分有證據——部分評分僅依據少量已報告指標。',
    'confidence_estimated': '可信度：僅根據文件文字估算——應視作假設。',
    'kpi_5d': '影響力五個維度評分',
    'kpi_5d_sub': '等級 {grade} · {evidence}',
    'kpi_sdg': '首要可持續發展目標',
    'kpi_sdg_none': '未有重要目標',
    'kpi_gw': '漂綠風險',
    'kpi_evidence': '證據',
    'kpi_evidence_value': '{claims} 項聲明',
    'kpi_evidence_sub': '{metrics} 項 IRIS+ 指標 · 盡職調查覆蓋 {dd}%',
    'kpi_evidence_sub_nodd': '{metrics} 項 IRIS+ 指標',
    'evidence-based': '有證據',
    'partial': '部分證據',
    'estimated': '估算',
    'sec_mind': '甚麼會改變我們的判斷',
    'lede_mind': '最能影響本評估的三項證據。',
    'mind_metric': '報告{name}（{id}）',
    'mind_metric_why': '{dimension}是最弱的維度（{score}/5，{evidence}）；這是該行業的核心指標。',
    'mind_verify': '主要聲明的獨立核實',
    'mind_verify_why': '主要成果未見第三方核實或審計。',
    'mind_outcome': '附基線或對照組的成果證據',
    'mind_outcome_why': '大部分聲明顯示變化但未能歸因（NESTA 第 2 級）；加入對照可提升至第 3 級。',
    'mind_adverse': '該行業的負面影響指標',
    'mind_adverse_why': '只報告正面指標；遺漏會提高漂綠風險。',
    'mind_dd': '回答：{question}',
    'mind_dd_why': '文件未有回答的高優先盡職調查問題。',
    'sec_5d': '影響力五個維度',
    'lede_5d': '評分 1–5。刻度線代表行業基準（如有）。',
    'dim_what': '甚麼',
    'dim_who': '誰',
    'dim_how_much': '多少',
    'dim_contribution': '貢獻',
    'dim_risk': '風險',
    'legend_score': '公司評分',
    'legend_bench': '行業基準',
    'table_view': '以表格顯示',
    'col_dimension': '維度',
    'col_score': '評分',
    'col_benchmark': '基準',
    'col_evidence': '證據',
    'col_notes': '備註',
    'sec_sdg': '可持續發展目標對應',
    'lede_sdg': '只列出重要目標（公司聲稱、由業務推斷或有目標專屬指標佐證），評分 0–100。',
    'sdg_other': '其他目標（僅供參考）：{goals}',
    'sdg_none': '尚無重要目標——請報告目標專屬的 IRIS+ 指標。',
    'col_goal': '目標',
    'col_confidence': '可信度',
    'col_metrics': '對應指標',
    'sec_evidence': '證據清單',
    'lede_evidence': '文件中找到的每項聲明及評分所用的每項指標。',
    'col_claim': '聲明',
    'col_type': '類型',
    'col_level': 'NESTA 級別',
    'col_signals': '證據',
    'col_metric': '指標',
    'col_value': '數值',
    'col_origin': '來源',
    'origin_reported': '已報告',
    'origin_extracted': '從文字擷取',
    'origin_derived': '推算',
    'claims_caption': '聲明（{n}）',
    'metrics_caption': '指標（{n}）',
    'no_claims': '未有擷取到聲明。',
    'signal_third_party_verified': '第三方核實',
    'signal_audited': '已審計',
    'signal_certified': '已認證',
    'signal_controlled_evaluation': '對照評估',
    'signal_baseline_comparison': '基線比較',
    'sec_gw': '漂綠審查',
    'lede_gw': '0–100 風險評分的組成部分。60 或以上屬實質發現；低於 60 多反映資料缺失。',
    'gw_claim_metric_gap': '聲明欠缺指標',
    'gw_adverse_omission': '遺漏負面影響',
    'gw_specificity': '措辭含糊',
    'gw_selectivity': '選擇性報告',
    'gw_verification': '未經核實',
    'legend_component': '風險組成（0–100）',
    'legend_threshold': '發現門檻（60）',
    'flags': '警示',
    'sec_risks': '風險與機遇',
    'risks_disclosed': '文件中披露',
    'risks_sector': '行業常見風險——盡職調查時查核',
    'opportunities': '機遇',
    'sec_actions': '行動計劃',
    'lede_actions': '已去重的下一步，按重要性排列。',
    'area_metrics': '指標',
    'area_evidence': '證據',
    'area_sdg': '可持續發展目標',
    'area_risk': '風險',
    'area_5d': '影響',
    'area_evidence_quality': '證據質素',
    'sec_targets': '影響目標',
    'col_target': '目標',
    'col_current': '現況',
    'col_status': '狀態',
    'sec_feedback': '受益人回饋',
    'sec_appendix': '方法及釋義',
    'method_title': '本報告的編製方法',
    'method_1': '從文件擷取聲明，並按 NESTA 證據標準評級；只有在單位及語境明確時，才把數量對應至 IRIS+ 指標編號。',
    'method_2': '影響力五個維度評分（1–5）在有已報告指標時以指標為依據，否則以文件文字估算；證據標籤會註明。',
    'method_3': '可持續發展目標評分（0–100）結合目標專屬指標覆蓋、業務推斷及影響主題；跨領域指標權重較低。',
    'method_4': '漂綠風險權重：聲明欠缺指標（30%）、遺漏負面影響（20%）、措辭含糊（20%）、選擇性報告（15%）及未經核實（15%）。',
    'method_5': '投資委員會關卡套用基金論點的門檻；因資料缺失而未通過的項目列為證據不足，而非負面發現。',
    'glossary_title': '本報告用語',
    'generated_by': '由 Impact Vision 生成——開源影響力衡量工具。',
    'kpis_label': '重點數字',
    'col_area': '範疇',
    'fb_satisfaction': '滿意度',
    'fb_nps': '淨推薦值',
    'fb_respondents': '受訪人數',
    'conf_high': '高可信度',
    'conf_medium': '中等可信度',
    'conf_low': '低可信度',
    'rec_pass': '所有關卡均已通過——可提交投資委員會。',
    'rec_warn': '最終批核前請處理警示項目。',
    'rec_insufficient': '未通過的項目反映證據不足，並非負面發現。請收集缺失的指標及盡職調查答案後重新評估。',
    'rec_fail': '提交投資委員會前請解決阻擋項目並重新評估。',
    'check_5D overall score': '五個維度總分',
    'check_Top SDG score': '首要可持續發展目標評分',
    'check_DD checklist coverage': '盡職調查覆蓋率',
    'check_Greenwashing risk': '漂綠風險',
    'check_Exclusion screening': '排除篩選',
    'check_Forbidden sector check': '禁止行業',
    'check_Required sector check': '指定行業',
    'bound_min': '最低',
    'bound_max': '最高',
    'gwc_Genuine Impact Leader': '真正的影響力領先者',
    'gwc_Substantive with Gaps': '實質但有缺口',
    'gwc_Moderate Risk': '中等風險',
    'gwc_High Risk': '高風險',
    'gwc_Probable Greenwashing': '很可能漂綠',
    'lang_note': '引用的聲明、建議及行業風險以原文顯示。',
    'sec_glance': '影響一覽',
    'lede_glance': '重要的可持續發展目標，以及公司活動如何帶來成果（根據文件中的聲明）。',
    'wheel_center': '項重要目標',
    'stage_activities': '業務內容',
    'stage_outputs': '產出',
    'stage_outcomes': '成果',
    'stage_targets': '目標',
    'stage_empty': '尚未報告',
    'pill_pass': '可推進',
    'pill_warn': '有條件',
    'pill_insufficient': '未可提交',
    'pill_fail': '不建議推進',
    'tile_threshold': '發現門檻 60',
    'mix_legend': '按 NESTA 證據級別劃分的聲明（1→5）',
}

ZH_CN: dict[str, str] = {
    'doc_title': '影响评估',
    'eyebrow': '影响评估',
    'generated': '生成日期 {date}',
    'standard': 'IRIS+ {version}',
    'source': '来源：{source}',
    'skip': '跳至报告',
    'contents': '目录',
    'notice_full': '机密——供内部投资及有限合伙人使用。',
    'notice_ic': '机密——供投资委员会使用。',
    'notice_lp': '机密——供基金有限合伙人使用。',
    'notice_regulator': '供监管审阅。',
    'notice_public': '供公开披露。',
    'sec_verdict': '建议',
    'verdict_pass': '可提交投资委员会',
    'verdict_warn': '有条件——提交投资委员会前须处理',
    'verdict_insufficient': '未可提交投资委员会——证据不足',
    'verdict_fail': '不建议推进',
    'verdict_unknown': '未执行投资委员会关卡',
    'why': '原因',
    'missing_data': '数据缺失',
    'confidence_evidence-based': '置信度：评分以已报告指标为依据。',
    'confidence_partial': '置信度：部分有证据——部分评分仅依据少量已报告指标。',
    'confidence_estimated': '置信度：仅根据文件文字估算——应视作假设。',
    'kpi_5d': '影响力五个维度评分',
    'kpi_5d_sub': '等级 {grade} · {evidence}',
    'kpi_sdg': '首要可持续发展目标',
    'kpi_sdg_none': '未有重要目标',
    'kpi_gw': '漂绿风险',
    'kpi_evidence': '证据',
    'kpi_evidence_value': '{claims} 项声明',
    'kpi_evidence_sub': '{metrics} 项 IRIS+ 指标 · 尽职调查覆盖 {dd}%',
    'kpi_evidence_sub_nodd': '{metrics} 项 IRIS+ 指标',
    'evidence-based': '有证据',
    'partial': '部分证据',
    'estimated': '估算',
    'sec_mind': '什么会改变我们的判断',
    'lede_mind': '最能影响本评估的三项证据。',
    'mind_metric': '报告{name}（{id}）',
    'mind_metric_why': '{dimension}是最弱的维度（{score}/5，{evidence}）；这是该行业的核心指标。',
    'mind_verify': '主要声明的独立核实',
    'mind_verify_why': '主要成果未见第三方核实或审计。',
    'mind_outcome': '附基线或对照组的成果证据',
    'mind_outcome_why': '大部分声明显示变化但未能归因（NESTA 第 2 级）；加入对照可提升至第 3 级。',
    'mind_adverse': '该行业的负面影响指标',
    'mind_adverse_why': '只报告正面指标；遗漏会提高漂绿风险。',
    'mind_dd': '回答：{question}',
    'mind_dd_why': '文件未有回答的高优先尽职调查问题。',
    'sec_5d': '影响力五个维度',
    'lede_5d': '评分 1–5。刻度线代表行业基准（如有）。',
    'dim_what': '什么',
    'dim_who': '谁',
    'dim_how_much': '多少',
    'dim_contribution': '贡献',
    'dim_risk': '风险',
    'legend_score': '公司评分',
    'legend_bench': '行业基准',
    'table_view': '以表格显示',
    'col_dimension': '维度',
    'col_score': '评分',
    'col_benchmark': '基准',
    'col_evidence': '证据',
    'col_notes': '备注',
    'sec_sdg': '可持续发展目标对应',
    'lede_sdg': '只列出重要目标（公司声称、由业务推断或有目标专属指标佐证），评分 0–100。',
    'sdg_other': '其他目标（仅供参考）：{goals}',
    'sdg_none': '尚无重要目标——请报告目标专属的 IRIS+ 指标。',
    'col_goal': '目标',
    'col_confidence': '置信度',
    'col_metrics': '对应指标',
    'sec_evidence': '证据清单',
    'lede_evidence': '文件中找到的每项声明及评分所用的每项指标。',
    'col_claim': '声明',
    'col_type': '类型',
    'col_level': 'NESTA 级别',
    'col_signals': '证据',
    'col_metric': '指标',
    'col_value': '数值',
    'col_origin': '来源',
    'origin_reported': '已报告',
    'origin_extracted': '从文字撷取',
    'origin_derived': '推算',
    'claims_caption': '声明（{n}）',
    'metrics_caption': '指标（{n}）',
    'no_claims': '未有撷取到声明。',
    'signal_third_party_verified': '第三方核实',
    'signal_audited': '已审计',
    'signal_certified': '已认证',
    'signal_controlled_evaluation': '对照评估',
    'signal_baseline_comparison': '基线比较',
    'sec_gw': '漂绿审查',
    'lede_gw': '0–100 风险评分的组成部分。60 或以上属实质发现；低于 60 多反映数据缺失。',
    'gw_claim_metric_gap': '声明欠缺指标',
    'gw_adverse_omission': '遗漏负面影响',
    'gw_specificity': '措辞含糊',
    'gw_selectivity': '选择性报告',
    'gw_verification': '未经核实',
    'legend_component': '风险组成（0–100）',
    'legend_threshold': '发现门槛（60）',
    'flags': '警示',
    'sec_risks': '风险与机遇',
    'risks_disclosed': '文件中披露',
    'risks_sector': '行业常见风险——尽职调查时查核',
    'opportunities': '机遇',
    'sec_actions': '行动计划',
    'lede_actions': '已去重的下一步，按重要性排列。',
    'area_metrics': '指标',
    'area_evidence': '证据',
    'area_sdg': '可持续发展目标',
    'area_risk': '风险',
    'area_5d': '影响',
    'area_evidence_quality': '证据质量',
    'sec_targets': '影响目标',
    'col_target': '目标',
    'col_current': '现况',
    'col_status': '状态',
    'sec_feedback': '受益人回馈',
    'sec_appendix': '方法及释义',
    'method_title': '本报告的编制方法',
    'method_1': '从文件撷取声明，并按 NESTA 证据标准评级；只有在单位及语境明确时，才把数量对应至 IRIS+ 指标编号。',
    'method_2': '影响力五个维度评分（1–5）在有已报告指标时以指标为依据，否则以文件文字估算；证据标签会注明。',
    'method_3': '可持续发展目标评分（0–100）结合目标专属指标覆盖、业务推断及影响主题；跨领域指标权重较低。',
    'method_4': '漂绿风险权重：声明欠缺指标（30%）、遗漏负面影响（20%）、措辞含糊（20%）、选择性报告（15%）及未经核实（15%）。',
    'method_5': '投资委员会关卡套用基金论点的门槛；因数据缺失而未通过的项目列为证据不足，而非负面发现。',
    'glossary_title': '本报告用语',
    'generated_by': '由 Impact Vision 生成——开源影响力衡量工具。',
    'kpis_label': '重点数字',
    'col_area': '范畴',
    'fb_satisfaction': '满意度',
    'fb_nps': '净推荐值',
    'fb_respondents': '受访人数',
    'conf_high': '高置信度',
    'conf_medium': '中等置信度',
    'conf_low': '低置信度',
    'rec_pass': '所有关卡均已通过——可提交投资委员会。',
    'rec_warn': '最终批核前请处理警示项目。',
    'rec_insufficient': '未通过的项目反映证据不足，并非负面发现。请收集缺失的指标及尽职调查答案后重新评估。',
    'rec_fail': '提交投资委员会前请解决阻挡项目并重新评估。',
    'check_5D overall score': '五个维度总分',
    'check_Top SDG score': '首要可持续发展目标评分',
    'check_DD checklist coverage': '尽职调查覆盖率',
    'check_Greenwashing risk': '漂绿风险',
    'check_Exclusion screening': '排除筛选',
    'check_Forbidden sector check': '禁止行业',
    'check_Required sector check': '指定行业',
    'bound_min': '最低',
    'bound_max': '最高',
    'gwc_Genuine Impact Leader': '真正的影响力领先者',
    'gwc_Substantive with Gaps': '实质但有缺口',
    'gwc_Moderate Risk': '中等风险',
    'gwc_High Risk': '高风险',
    'gwc_Probable Greenwashing': '很可能漂绿',
    'lang_note': '引用的声明、建议及行业风险以原文显示。',
    'sec_glance': '影响一览',
    'lede_glance': '重要的可持续发展目标，以及公司活动如何带来成果（根据文件中的声明）。',
    'wheel_center': '项重要目标',
    'stage_activities': '业务内容',
    'stage_outputs': '产出',
    'stage_outcomes': '成果',
    'stage_targets': '目标',
    'stage_empty': '尚未报告',
    'pill_pass': '可推进',
    'pill_warn': '有条件',
    'pill_insufficient': '未可提交',
    'pill_fail': '不建议推进',
    'tile_threshold': '发现门槛 60',
    'mix_legend': '按 NESTA 证据级别划分的声明（1→5）',
}

SDG_NAMES_ZH_HK: dict[int, str] = {1: '無貧窮', 2: '零飢餓', 3: '良好健康與福祉', 4: '優質教育', 5: '性別平等', 6: '清潔飲水和衛生設施', 7: '經濟適用的清潔能源', 8: '體面工作和經濟增長', 9: '產業、創新和基礎設施', 10: '減少不平等', 11: '可持續城市和社區', 12: '負責任消費和生產', 13: '氣候行動', 14: '水下生物', 15: '陸地生物', 16: '和平、正義與強大機構', 17: '促進目標實現的夥伴關係'}

SDG_NAMES_ZH_CN: dict[int, str] = {1: '无贫穷', 2: '零饥饿', 3: '良好健康与福祉', 4: '优质教育', 5: '性别平等', 6: '清洁饮水和卫生设施', 7: '经济适用的清洁能源', 8: '体面工作和经济增长', 9: '产业、创新和基础设施', 10: '减少不平等', 11: '可持续城市和社区', 12: '负责任消费和生产', 13: '气候行动', 14: '水下生物', 15: '陆地生物', 16: '和平、正义与强大机构', 17: '促进目标实现的伙伴关系'}

SECTORS_ZH_HK: dict[str, str] = {
    'agriculture': '農業',
    'livestock': '畜牧',
    'energy': '能源',
    'fintech': '金融科技',
    'healthcare': '醫療保健',
    'education': '教育',
    'water': '水務',
    'real estate': '房地產',
    'construction': '建造',
    'manufacturing': '製造業',
    'transport': '運輸',
    'logistics': '物流',
    'tourism': '旅遊',
    'retail': '零售',
    'mining': '採礦',
    'media': '媒體',
    'technology': '科技',
    'ict': '資訊及通訊科技',
    'waste management': '廢物管理',
    'professional services': '專業服務',
}

SECTORS_ZH_CN: dict[str, str] = {
    'agriculture': '农业',
    'livestock': '畜牧',
    'energy': '能源',
    'fintech': '金融科技',
    'healthcare': '医疗保健',
    'education': '教育',
    'water': '水务',
    'real estate': '房地产',
    'construction': '建筑',
    'manufacturing': '制造业',
    'transport': '运输',
    'logistics': '物流',
    'tourism': '旅游',
    'retail': '零售',
    'mining': '采矿',
    'media': '媒体',
    'technology': '科技',
    'ict': '信息通信技术',
    'waste management': '废物管理',
    'professional services': '专业服务',
}

STRINGS: dict[str, dict[str, str]] = {"en": EN, "zh-HK": ZH_HK, "zh-CN": ZH_CN}
SDG_NAMES: dict[str, dict[int, str]] = {"zh-HK": SDG_NAMES_ZH_HK, "zh-CN": SDG_NAMES_ZH_CN}
SECTOR_NAMES: dict[str, dict[str, str]] = {"zh-HK": SECTORS_ZH_HK, "zh-CN": SECTORS_ZH_CN}

_ALIASES = {
    "zh-hk": "zh-HK", "zh-tw": "zh-HK", "zh-hant": "zh-HK", "zh-mo": "zh-HK",
    "zh": "zh-CN", "zh-cn": "zh-CN", "zh-hans": "zh-CN", "zh-sg": "zh-CN",
}


def normalize_lang(lang: str | None) -> str:
    """'zh_hk' / 'zh-Hant' → 'zh-HK'; unknown → 'en'."""
    key = (lang or "en").strip().replace("_", "-").lower()
    if key in ("", "en") or key.startswith("en-"):
        return "en"
    return _ALIASES.get(key, "en")


def translator(lang: str = "en") -> Callable[..., str]:
    """Return ``t(key, **fmt)`` for *lang*, falling back to English."""
    table = STRINGS.get(normalize_lang(lang), EN)

    def t(key: str, **fmt: object) -> str:
        text = table[key] if key in table else EN.get(key, key)
        return text.format(**fmt) if fmt else text

    return t


__all__ = ["EN", "SDG_NAMES", "SECTOR_NAMES", "STRINGS", "normalize_lang", "translator"]
